### ISSUE TITLE
Why're we using __init__.py?

### ISSUE THREAD

**Issue by varunchopra** [TheGU/gdrive-upload#1]
Just curious, as I'm a bit new to this. Is there a reason for using `__init__.py`?

Also, the script throws an error unless you change:

```
from .gdrive_authen import create_gdrive_service
from .gdrive_uploader import upload_file
```
to
```
from gdrive_authen import create_gdrive_service
from gdrive_uploader import upload_file
```

I'm using Python 3.6.

**Comment by TheGU** [comment]
I put `__init__.py` to make it a [package](https://docs.python.org/2/tutorial/modules.html#packages) when you clone this code to subfolder in another project. 

The layout should be something like this:
```
main.py
gdrive-upload/
    __init__.py
    gdrive_uploader.py
    upload.py 
    ...
```

And the script throw error because it expect to be use as a module so import section that throw error are [relative import for module](https://docs.python.org/2/tutorial/modules.html#intra-package-references). Try to change the code folder structure as above should solve the problem. This should also work in python 3.

Maybe I should try to run it again in python 3 and improve the readme manual. Thanks for your question.

**Comment by TheGU** [comment]
Just update the code to easier understanding and avoid error in https://github.com/TheGU/gdrive-upload/commit/8f9dc2451761f7ff88cee52c377af40f538f2056 . Please check read me and pull new code.
